displayName=Explorer Mode
author=Wyrdras
description=A plugin to help players regain a sense of discovery when playing the game by hiding the map until they reach a location.
tags=map, quest, explore, roleplay
plugins=com.explorerMode.ExplorerModePlugin